#!/usr/bin/perl


=head1 NAME

ana-dot

=head1 SYNOPSIS

        ana-dot word1 word2

=head1 DESCRIPTION

Given two words that are anagrams,
generate the conflict graph for the two words
and print out its description in the DOT language
for layout with GraphViz.

On standard error, prints a listing of the graph's connected components
and the vertices in one of its maximal independent sets.

=cut

use Ana;
use Ana::Graph;
@ARGV == 2 or die "Usage: ana-dot anagram-a anagram-b\n";

my ($a, $b) = @ARGV;
Ana::are_anagrams($a, $b) or die "Those words are not anagrams.\n";

my $G = Ana::Graph->new_from_words($a, $b);
print $G->to_dot;

print STDERR "Components:\n";
for my $c ($G->components) {
  print STDERR "@$c\n";
}

print STDERR "\nMaximal independent set:\n";
my @mis = $G->mis;
print STDERR "  @mis\n";


__END__
mordant dormant  : 3 vertices, no edges
acrididae cidaridae : 11 vertices, 11 edges, mis 4
