#!/usr/bin/perl

=head1 NAME

simple

=head1 SYNOPSIS

        simple [dictionary-files...]

=head1 DESCRIPTION

Read in lists of words
and emits a sorted anagram list
in alphabetic order.

=cut

# Process word list
while (my $word = <>) {
  next if $seen{$word}++;
  chomp $word;
  my $sorted = join "", sort split //, $word;
  push @{$anagrams{lc $sorted}}, $word;
}

for my $words (values %anagrams) {
  print "@$words\n" if @$words > 1;
}
